// Static fake-candidate data shown to free-tier users as a blurred preview
// behind the paywall overlay. Subscribers never see this data; this module is
// code-split (dynamic-imported from _browse-client.tsx) so the ~6–10 KB of
// fake profiles isn't shipped to paying users.
// Phase 4 Bundle C.

import type { Card } from "./_browse-client";

export const BLURRED_PREVIEW_CARDS: Card[] = [
  {
    id: "preview-1",
    name: "Bilal R.",
    initials: "BR",
    role: "Senior Software Engineer",
    type: "Engineer",
    skills: ["React", "Node.js", "TypeScript", "AWS"],
    location: "Lahore, Pakistan",
    exp: "6 years",
    available: true,
    score: 92,
    highlights: ["6 yrs experience"],
    bio: "Full-stack engineer with strong product sense.",
    fullTime: true,
    partTime: false,
    remote: true,
    lastActive: "Today",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-2",
    name: "Hira S.",
    initials: "HS",
    role: "Product Designer",
    type: "Design",
    skills: ["Figma", "Design Systems", "User Research"],
    location: "Karachi, Pakistan",
    exp: "5 years",
    available: true,
    score: 88,
    highlights: ["Design systems lead"],
    bio: "Product designer focused on B2B SaaS workflows.",
    fullTime: true,
    partTime: true,
    remote: true,
    lastActive: "Yesterday",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-3",
    name: "Usman K.",
    initials: "UK",
    role: "Sales Development Rep",
    type: "SDR",
    skills: ["HubSpot", "Salesforce", "Cold Outreach"],
    location: "Islamabad, Pakistan",
    exp: "3 years",
    available: true,
    score: 85,
    highlights: ["Top quota attainment"],
    bio: "SDR with consistent quota attainment.",
    fullTime: true,
    partTime: false,
    remote: true,
    lastActive: "Today",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-4",
    name: "Ayesha M.",
    initials: "AM",
    role: "Customer Success Manager",
    type: "CS",
    skills: ["Gainsight", "Onboarding", "QBRs"],
    location: "Multan, Pakistan",
    exp: "4 years",
    available: true,
    score: 90,
    highlights: ["NPS uplift"],
    bio: "CS lead specializing in onboarding US SaaS clients.",
    fullTime: true,
    partTime: true,
    remote: true,
    lastActive: "2 days ago",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-5",
    name: "Tariq H.",
    initials: "TH",
    role: "Data Scientist",
    type: "Data",
    skills: ["Python", "TensorFlow", "SQL"],
    location: "Faisalabad, Pakistan",
    exp: "7 years",
    available: false,
    score: 94,
    highlights: ["ML in production"],
    bio: "Data scientist shipping ML pipelines at scale.",
    fullTime: true,
    partTime: false,
    remote: true,
    lastActive: "1 week ago",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-6",
    name: "Sana A.",
    initials: "SA",
    role: "DevOps Engineer",
    type: "DevOps",
    skills: ["AWS", "Terraform", "Kubernetes"],
    location: "Lahore, Pakistan",
    exp: "5 years",
    available: true,
    score: 87,
    highlights: ["Cut infra cost 35%"],
    bio: "DevOps engineer reducing infra cost via automation.",
    fullTime: true,
    partTime: false,
    remote: true,
    lastActive: "Today",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-7",
    name: "Hassan I.",
    initials: "HI",
    role: "QA Automation Engineer",
    type: "QA",
    skills: ["Cypress", "Selenium", "Jest"],
    location: "Karachi, Pakistan",
    exp: "4 years",
    available: true,
    score: 82,
    highlights: ["80% test coverage"],
    bio: "QA engineer focused on automation frameworks.",
    fullTime: true,
    partTime: true,
    remote: true,
    lastActive: "Yesterday",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-8",
    name: "Mehwish K.",
    initials: "MK",
    role: "Performance Marketing Lead",
    type: "Marketing",
    skills: ["Google Ads", "Meta Ads", "Analytics"],
    location: "Islamabad, Pakistan",
    exp: "6 years",
    available: true,
    score: 89,
    highlights: ["ROAS 4x+"],
    bio: "Performance marketer managing 6-figure ad budgets.",
    fullTime: true,
    partTime: false,
    remote: true,
    lastActive: "3 days ago",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-9",
    name: "Faisal Q.",
    initials: "FQ",
    role: "Business Operations Manager",
    type: "Ops",
    skills: ["Notion", "Process Design", "OKRs"],
    location: "Lahore, Pakistan",
    exp: "8 years",
    available: true,
    score: 91,
    highlights: ["Scaled ops 5x"],
    bio: "Ops manager scaling startups from seed to Series B.",
    fullTime: true,
    partTime: false,
    remote: true,
    lastActive: "Today",
    github: null,
    linkedin: null,
  },
  {
    id: "preview-10",
    name: "Zainab N.",
    initials: "ZN",
    role: "Senior Accountant",
    type: "Finance",
    skills: ["QuickBooks", "Xero", "ACCA"],
    location: "Multan, Pakistan",
    exp: "5 years",
    available: true,
    score: 78,
    highlights: ["ACCA qualified"],
    bio: "ACCA-qualified accountant managing remote-client books.",
    fullTime: true,
    partTime: true,
    remote: true,
    lastActive: "Yesterday",
    github: null,
    linkedin: null,
  },
];
