ARG MINICONDA_VERSION="Miniconda3-latest-Linux-x86_64.sh"
ARG CUDA_VERSION="11.7.1-cudnn8-runtime-ubuntu22.04"
ARG USERNAME=colossyan

FROM nvidia/cuda:$CUDA_VERSION

WORKDIR /code

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends wget && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/code/miniconda3/bin:${PATH}"
ARG PATH="/code/miniconda3/bin:${PATH}"

ARG MINICONDA_VERSION
# Installing miniconda
RUN mkdir /miniconda3 \
    && wget https://repo.anaconda.com/miniconda/$MINICONDA_VERSION -O /miniconda3/$MINICONDA_VERSION \
    && bash /miniconda3/$MINICONDA_VERSION -u -b -p /code/miniconda3 /miniconda3 \
    && rm -f /miniconda3/$MINICONDA_VERSION

COPY environment.yaml .
RUN conda update -n base -c defaults conda
RUN conda env create -f environment.yaml && \
    conda clean --all -y

# Make RUN commands use the new environment
SHELL ["conda", "run", "-n", "env", "/bin/bash", "-c"]

ENV UID=1000 \
    GID=1000

ARG USERNAME

RUN groupadd --gid $GID $USERNAME \
    && useradd --uid $UID --gid $GID -m $USERNAME \
    && chown -R $UID:$GID /code /miniconda3

COPY /config ./config
COPY /scripts ./scripts
COPY main.py .

USER $USERNAME
CMD ["conda", "run", "-n", "env", "--no-capture-output", "python", "-u", "main.py"]
